### ISSUE TITLE
Invalid School name

### ISSUE THREAD

**Issue by johanneslosch** [alex-lushiku/untis-to-google-calendar#1]
if I enter my school name I get this error message

`
(node:7820) UnhandledPromiseRejectionWarning: Error: Failed to login. {"jsonrpc":"2.0","id":"error","error":{"message":"invalid schoolname","code":-8500}}
    at WebUntis.login (C:\Users\Hannes\Documents\dev\test\untis-to-google-calendar\node_modules\webuntis\index.js:91:10)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:7820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by johanneslosch** [comment]
okay I found the right name of my school, thanks for your code!
